services:
  smaku-mysql:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: tz-test
      MYSQL_ROOT_PASSWORD: tz-test
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default_authentication_plugin=mysql_native_password --skip-log-bin --log-error-verbosity=1
    volumes:
      - ./data:/var/lib/mysql
    container_name: tz-test-mysql
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - --host=localhost
        - --port=3306
        - --user=root
        - --password=tz-test
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
